name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Run tests
        run: uv run python -m unittest discover -s tests

      - name: Install ruff
        run: uv sync --dev

      - name: Run ruff
        run: uv run ruff check .
